### ISSUE TITLE
About the split2 of Sketchy

### ISSUE THREAD

**Issue by tiangarin** [gr8joo/IIAE#3]
Thank you for your work. I'm curious about the results of IIAE on split2 of Sketchy, which strictly follows the zero-shot setting. If there are no direct results, can you tell me how to get the split2 features based on the split1 features you provided?

**Comment by gr8joo** [comment]
Hi,

I am afraid I misunderstood your question. What do you mean by split2?

The only data split that I used to report the results in our paper is split1 (seems like you call the data split I use as split1) which is chosen by [SEM-PCYC](https://github.com/AnjanDutta/sem-pcyc).

**Comment by gr8joo** [comment]
Please ignore the previous reply (sorry for my poor memory)!
Split2 corresponds to the class split (train/test) from [doodle2search](https://github.com/sounakdey/doodle2search).

Among those two splits, the main reason we decided to use split1 from [SEM-PCYC](https://github.com/AnjanDutta/sem-pcyc) is that we found [LCALE](https://ojs.aaai.org/index.php/AAAI/article/view/6817) which was the newest baseline method at the moment with some similarity to ours (from the usage of VAE-based architecture).
We were able to compare its performance to ours in Table 3 by adopting split1, which was also used by [LCALE](https://ojs.aaai.org/index.php/AAAI/article/view/6817).

Unfortunately, I don't have any 'valid' features of split2, since I extracted features of both splits 1&2 from the same VGG models pretrained by [SEM-PCYC](https://github.com/AnjanDutta/sem-pcyc).
Thus, some of test classes chosen by [doodle2search](https://github.com/sounakdey/doodle2search) should be exposed to the procedure of pretraining the VGG models that I used.
This is another reason we reported the performance only in the split1 and discarded split2 in the end.

I think you should be able to extract 'valid' features of split2 using [doodle2search](https://github.com/sounakdey/doodle2search) codebase.

Sorry for the confusion from the previous reply.

**Comment by gr8joo** [comment]
Since the issue has been left inactive for a month, I'd like to close it.
Please reopen it if you still have any related concerns.
