### ISSUE TITLE
 Sketchy Extended dataset

### ISSUE THREAD

**Issue by iuhnayoug** [gr8joo/IIAE#4]
Hi, thanks for your work. Could you please share a link to download the Sketchy Extended dataset rather than the features? 
I fail to download it from both https://github.com/sounakdey/doodle2search and https://github.com/AnjanDutta/sem-pcyc. It seems the original database author canceled the open link. It will be helpful for me. Thank you in advance!

**Comment by gr8joo** [comment]
Hi, sorry for the late response.

I am afraid that I am not eligible to share the original Sketchy Extended dataset, since there might be some license issue.
(Maybe those two links are blocked due to the license issue as well..?)

I think you should directly contact the publisher(s) of the dataset if you do need the original data rather than the features.

Let me close this issue since it is not necessarily an issue in this repo.
